# Generated by Django 3.1.5 on 2021-02-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0002_auto_20210206_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.comment'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reviews',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.review'),
        ),
    ]
