# Generated by Django 3.1.5 on 2021-02-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0003_auto_20210206_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='r8scholar.comment'),
        ),
    ]
