# Generated by Django 3.1.5 on 2021-02-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0005_auto_20210207_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('courses_rating', models.IntegerField(default=None)),
                ('instructors_rating', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='review',
            name='numb_reports',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='numb_reports',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.comment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.subject')),
            ],
        ),
    ]
