# Generated by Django 3.1.5 on 2021-02-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0006_auto_20210207_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.AddField(
            model_name='forum',
            name='subject_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.subject'),
        ),
        migrations.AddField(
            model_name='review',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='r8scholar.subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='r8scholar.subject'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='r8scholar.subject'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='r8scholar.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=202),
        ),
    ]
