# Generated by Django 3.1.5 on 2021-02-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0007_auto_20210207_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='r8scholar.subject'),
        ),
    ]
