# Generated by Django 3.1.5 on 2021-02-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0008_auto_20210207_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
