# Generated by Django 3.1.5 on 2021-02-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0009_auto_20210207_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
