# Generated by Django 3.1.5 on 2021-02-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0013_auto_20210214_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='overall_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='department',
            name='review',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.review'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='reviews',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='r8scholar.review'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='department',
            name='courses_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='department',
            name='instructors_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='rating',
            field=models.FloatField(default=None),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None, null=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
