# Generated by Django 3.1.5 on 2021-02-14 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('r8scholar', '0014_auto_20210214_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='nickname_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
