# Generated by Django 3.1.5 on 2021-03-22 20:40

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[api.validators.validate_brock_mail], verbose_name='email')),
                ('nickname', models.CharField(default=uuid.uuid4, max_length=25, unique=True)),
                ('password', models.CharField(max_length=100, validators=[api.validators.password_validator])),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False)),
                ('min_length', models.IntegerField(default=4, verbose_name='min_length')),
                ('verification_code', models.CharField(default='HQFAO8', max_length=10)),
                ('is_verified', models.BooleanField(default=False, verbose_name='is_verified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('review_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('content', models.TextField(default=None)),
                ('date', models.DateTimeField(default=None)),
                ('numb_reports', models.IntegerField(default=None)),
                ('child', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('rating', models.FloatField(default=0)),
                ('course_full_name', models.CharField(default=None, max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('courses_rating', models.FloatField(default=0)),
                ('instructors_rating', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=None)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None, null=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(default=None, max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField(default=None, null=True)),
                ('rating', models.FloatField(default=None, validators=[api.validators.rating_validator])),
                ('numb_reports', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now=True)),
                ('review_type', models.CharField(max_length=25)),
                ('course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.course')),
                ('department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.department')),
                ('instructor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructor')),
                ('reviewer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.comment')),
                ('nickname_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.comment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_posts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.forum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reviews',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.review'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('comment_id', 'review_id'), name='comment_key'),
        ),
    ]
