# Generated by Django 3.1.5 on 2021-04-21 20:13

import api.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='comment',
            name='users_thumbs_downed',
            field=models.ManyToManyField(related_name='c_users_thumbs_downed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_thumbs_upped',
            field=models.ManyToManyField(related_name='c_users_thumbs_upped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='diff_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='diff_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='diff_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='diff_rating',
            field=models.FloatField(default=None, validators=[api.validators.rating_validator]),
        ),
        migrations.AddField(
            model_name='review',
            name='tag_1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='tag_2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='tag_3',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='users_reported',
            field=models.ManyToManyField(related_name='users_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='users_thumbs_downed',
            field=models.ManyToManyField(related_name='users_thumbs_downed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='users_thumbs_upped',
            field=models.ManyToManyField(related_name='users_thumbs_upped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_prof',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_pass_reset',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='PW5KNC', max_length=10),
        ),
    ]
