# Generated by Django 3.1.5 on 2021-02-28 02:54

import api.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default=[api.generators.generate_validation_code], max_length=6),
        ),
    ]
