# Generated by Django 3.1.5 on 2021-03-29 23:11

import api.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=uuid.uuid4, max_length=25, unique=True, validators=[api.validators.profanity_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='RD59T7', max_length=10),
        ),
    ]
