# Generated by Django 3.1.5 on 2021-03-23 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'course_full_name']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forum_posts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reviews',
        ),
        migrations.AddField(
            model_name='department',
            name='course_full_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='course_full_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_full_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='XZM24H', max_length=10),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.AddField(
            model_name='userreviews',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreviews',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.review'),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.review'),
        ),
        migrations.AddConstraint(
            model_name='userreviews',
            constraint=models.UniqueConstraint(fields=('email', 'review_id'), name='user_review_key'),
        ),
        migrations.AddConstraint(
            model_name='usercomments',
            constraint=models.UniqueConstraint(fields=('email', 'review_id', 'comment_id'), name='user_comment_key'),
        ),
    ]
