# Generated by Django 3.1.5 on 2021-03-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='MHS7O2', max_length=10),
        ),
    ]
