# Generated by Django 3.1.5 on 2021-03-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210303_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_full_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='5EX28H', max_length=10),
        ),
    ]
