# Generated by Django 3.1.5 on 2021-03-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210303_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='overall_rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='5DGB6V', max_length=10),
        ),
    ]
