# Generated by Django 3.1.5 on 2021-03-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210331_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='numb_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='VA37GK', max_length=10),
        ),
    ]
