# Generated by Django 3.1.5 on 2021-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210421_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='KKIKFW', max_length=10),
        ),
    ]
