# Generated by Django 3.1.5 on 2021-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210331_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_prof',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='CHRUPL', max_length=10),
        ),
    ]
