# Generated by Django 3.1.5 on 2021-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210406_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='percent_recommend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_pass_reset',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='percent_recommend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='percent_recommend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='would_take_again',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='N9ELYP', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='api.Tags'),
        ),
    ]
