# Generated by Django 3.1.5 on 2021-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210422_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='RF973Z', max_length=10),
        ),
    ]
