# Generated by Django 3.1.5 on 2021-03-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210303_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='department',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='review',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.course'),
        ),
        migrations.AddField(
            model_name='review',
            name='instructor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='75ZIF5', max_length=10),
        ),
    ]
